### PR TITLE
Added functionality to change step size of RandomWalk.generate

### PR DESCRIPTION
**Pull request by samueljamesbell**
Optional third parameter has been added to generate method to allow step of a constant size.

### CODE REVIEW

**Comment by egtann** [comment]
Looks great. Thanks!

**Comment by samueljamesbell** [comment]
No worries - thanks for accepting!

**Comment by samueljamesbell** [comment]
Any ideas on when this will be pushed to RubyGems?

**Comment by egtann** [comment]
Thanks for reminding me. It's available now

**Pull request merged**
